### ISSUE TITLE
Compile-time warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]

### ISSUE THREAD

**Issue by Arcank** [google/gemmlowp#106]
./third_party/gemmlowp/public/../internal/multi_thread_gemm.h:368:38: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
    int workers_count = tasks.size() - 1;
        ~~~~~~~~~~~~~   ~~~~~~~~~~~~~^~~
1 warning generated.

See https://github.com/google/gemmlowp/blob/master/internal/multi_thread_gemm.h#L368.

**Comment by bjacob** [comment]
Thanks for the report. This is not concerning, as the values here are always going to be in range for 'int', but always worth fixing a warning. I won't have time for this today, you're very welcome to make a pull request.
