### ISSUE TITLE
Recent fix causes 2.5x performance regression

### ISSUE THREAD

**Issue by andreasgal** [google/gemmlowp#108]
This fix causes a 2.5x performance regression in our internal benchmarks:

https://github.com/google/gemmlowp/pull/105

I'll try to post more information shortly @bjacob

**Comment by andreasgal** [comment]
Removing the outer for (int c = 0; c < cols; c += block_params.l2_cols) loop contributes to a small part of the runtime increase. I suspect this patch causes cache threshing for some reason. Digging around some more

**Comment by andreasgal** [comment]
block_params 36 256 128 2712 256 128
block_params 36 256 128 2712 256 128
block_params 36 256 128 2712 256 128
block_params 36 256 128 2712 256 128
block_params 36 256 128 2712 256 128
block_params 36 256 128 2712 256 128
block_params 36 256 128 2712 256 128
block_params 36 256 128 2712 256 128
block_params2 36 256 128 336 256 128
block_params2 36 256 128 348 256 128
block_params2 36 256 128 336 256 128
block_params2 36 256 128 348 256 128
block_params2 36 256 128 336 256 128
block_params2 36 256 128 336 256 128
block_params2 36 256 128 336 256 128
block_params2 36 256 128 336 256 128

block_params2 is the old way of calculating block_params per thread. block_params is the new value that is passed in from the main thread. 

    printf("block_params %d %d %d %d %d %d\n",
           block_params.l1_rows, block_params.l1_cols, block_params.l1_depth,
           block_params.l2_rows, block_params.l2_cols, block_params.l2_depth);
    printf("block_params2 %d %d %d %d %d %d\n",
           block_params2.l1_rows, block_params2.l1_cols, block_params2.l1_depth,
           block_params2.l2_rows, block_params2.l2_cols, block_params2.l2_depth);

l2_rows is much larger with this patch

**Comment by andreasgal** [comment]
if (l2_rhs_factor == 1.0f) {
      l2_rows = RoundUp<KernelFormat::kRows>(rows);
    } else {

l2_rhs_factor is 1.0f, so l2_rows always > rows

**Comment by andreasgal** [comment]
When the main thread sets up block_params "rows" has a different meaning that in each thread, which causes us to oversize the L2 cache in block_params

main: rows=676 cols=512 depth=256
thread: rows=84 cols=512 depth=256
thread: rows=96 cols=512 depth=256
thread: rows=84 cols=512 depth=256
thread: rows=84 cols=512 depth=256
thread: rows=84 cols=512 depth=256
thread: rows=76 cols=512 depth=256
thread: rows=84 cols=512 depth=256
thread: rows=84 cols=512 depth=256

**Comment by bjacob** [comment]
Thanks for catching the regression. The previous comment about rows having a different meaning sounds like a very plausible explanation of the bug.

That l2_rhs_factor is 1.0f is a x86-only tweak that was contributed by Intel, that can be reconsidered now. In fact the whole l2_rhs_factor thing is a bit of a rough aspect of our block params selection logic. The whole thing may be due for rethinking, once the immediate regression is fixed.

**Comment by andreasgal** [comment]
This fixes the issue. This also assumed backing out the code that prevents l2_cols blocking in addition otherwise we also slightly go beyond the calculated L2 cache sizes.

diff --git a/node-gemmlowp/third_party/gemmlowp/internal/block_params.h b/node-gemmlowp/third_party/gemmlowp/internal/block_params.h
index b2fc3ff785..5d199d1469 100644
--- a/node-gemmlowp/third_party/gemmlowp/internal/block_params.h
+++ b/node-gemmlowp/third_party/gemmlowp/internal/block_params.h
@@ -58,6 +58,9 @@ struct BlockParams {
                                int l2_bytes_to_use, float l2_rhs_factor,
                                int* out_l2_rows, int* out_l2_cols,
                                int* out_l2_depth) {
+    int per_thread_rows =
+      std::max(1, RoundUp<KernelFormat::kRows>(rows) / num_threads);
+
     int l2_rows = 0;
     int l2_cols = 0;
     int l2_depth = 0;
@@ -81,15 +84,16 @@ struct BlockParams {
     // dimension concerns only the LHS. Blocking only RHS matrix for L2 enhances
     // the performance on x86.
     if (l2_rhs_factor == 1.0f) {
-      l2_rows = RoundUp<KernelFormat::kRows>(rows);
+      l2_rows = RoundUp<KernelFormat::kRows>(per_thread_rows);
     } else {
       int max_cache_friendly_l2_rows =
           std::max(1, (l2_bytes_to_use - l2_depth * l2_cols) /
                           (num_threads * (l2_depth + 4 * l2_cols)));
       int min_l2_rows_blocks =
-          std::max(1, CeilQuotient(rows, max_cache_friendly_l2_rows));
+          std::max(1, CeilQuotient(per_thread_rows, max_cache_friendly_l2_rows));
       l2_rows =
-          RoundUp<KernelFormat::kRows>(CeilQuotient(rows, min_l2_rows_blocks));
+          RoundUp<KernelFormat::kRows>(CeilQuotient(per_thread_rows,
+                                                    min_l2_rows_blocks));
     }
 
     *out_l2_rows = l2_rows;

**Comment by andreasgal** [comment]
Yeah this is all a bit messy. How do you feel about trying something else here. We could auto-tune these parameters pretty easily. Each invocation is really fast so we a binary search we can probably nail down the best size quickly. I am not sure calculations get us good sizes because depending on L1 vs L2 vs L3 vs main memory latency spilling over cache might be better and it also depends how many cores are in use and how cache is shared and such. Wdyt?

**Comment by bjacob** [comment]
There is no question that an actual experimental determination can result in higher performance than a simple heuristic. At least, I would be OK with adding gemmlowp entry points allowing the user to take ownership of that problem (e.g. supplying BlockParams to use for a given GEMM). On the other hand, I have never seen such experimental determination of best block params be performed in a way that was simultaneously accurate enough to be useful, and fast enough to be an acceptable compromise for most users. It seems more practical to 1) fix the current bug, keeping only a heuristic to determine BlockParams, 2) add entry points to allow users to tweak BlockParams, 3) if and when a compelling experimental determination of BlockParams is developed, consider it for inclusion.

Returning to 1) and your previous comment:

> This fixes the issue. This also assumed backing out the code that prevents l2_cols blocking in addition otherwise we also slightly go beyond the calculated L2 cache sizes.

What do you mean by "This also assumed backing out the code..." : is this a fix for the regression introduced by my previous fix, or is this an improvement orthogonal to it and assuming it backed out already? If it is not a fix for the regression from my previous fix, then do we at this point know how we are going to get gemmlowp both fast and safe (as in my previous fix)?

**Comment by andreasgal** [comment]
Basically undo all changes in your patch and only make these changes to the original code:

```patch
diff --git a/node-gemmlowp/third_party/gemmlowp/internal/block_params.h b/node-gemmlowp/third_party/gemmlowp/internal/block_params.h
index b2fc3ff785..5d199d1469 100644
--- a/node-gemmlowp/third_party/gemmlowp/internal/block_params.h
+++ b/node-gemmlowp/third_party/gemmlowp/internal/block_params.h
@@ -58,6 +58,9 @@ struct BlockParams {
                                int l2_bytes_to_use, float l2_rhs_factor,
                                int* out_l2_rows, int* out_l2_cols,
                                int* out_l2_depth) {
+    int per_thread_rows =
+      std::max(1, RoundUp<KernelFormat::kRows>(rows) / num_threads);
+
     int l2_rows = 0;
     int l2_cols = 0;
     int l2_depth = 0;
@@ -81,15 +84,16 @@ struct BlockParams {
     // dimension concerns only the LHS. Blocking only RHS matrix for L2 enhances
     // the performance on x86.
     if (l2_rhs_factor == 1.0f) {
-      l2_rows = RoundUp<KernelFormat::kRows>(rows);
+      l2_rows = RoundUp<KernelFormat::kRows>(per_thread_rows);
     } else {
       int max_cache_friendly_l2_rows =
           std::max(1, (l2_bytes_to_use - l2_depth * l2_cols) /
                           (num_threads * (l2_depth + 4 * l2_cols)));
       int min_l2_rows_blocks =
-          std::max(1, CeilQuotient(rows, max_cache_friendly_l2_rows));
+          std::max(1, CeilQuotient(per_thread_rows, max_cache_friendly_l2_rows));
       l2_rows =
-          RoundUp<KernelFormat::kRows>(CeilQuotient(rows, min_l2_rows_blocks));
+          RoundUp<KernelFormat::kRows>(CeilQuotient(per_thread_rows,
+                                                    min_l2_rows_blocks));
     }
 
     *out_l2_rows = l2_rows;
diff --git a/node-gemmlowp/third_party/gemmlowp/internal/multi_thread_gemm.h b/node-gemmlowp/third_party/gemmlowp/internal/multi_thread_gemm.h
index 67904827d2..c5e8615117 100644
--- a/node-gemmlowp/third_party/gemmlowp/internal/multi_thread_gemm.h
+++ b/node-gemmlowp/third_party/gemmlowp/internal/multi_thread_gemm.h
@@ -420,6 +420,7 @@ struct GemmWithPackedRhsTask : Task {
                         const MatrixBlockBounds& _result_block,
                         const LhsOffset& _lhs_offset,
                         const RhsOffset& _rhs_offset,
+                        const BlockParams& _block_params,
                         const OutputPipelineType& _output_pipeline)
       : context(_context),
         kernel(_kernel),
@@ -429,22 +430,18 @@ struct GemmWithPackedRhsTask : Task {
         result_block(_result_block),
         lhs_offset(_lhs_offset),
         rhs_offset(_rhs_offset),
+        block_params(_block_params),
         output_pipeline(_output_pipeline) {}
 
   void Run() override {
     ScopedProfilingLabel label("GemmWithPackedRhsTask");
     TIMELINE_BLOCK("GemmWithPackedRhsTask");
+    assert(result_block.cols <= block_params.l2_cols);
 
     const int rows = result_block.rows;
     const int cols = result_block.cols;
     const int depth = lhs.cols();
 
-    BlockParams block_params;
-    block_params.Init<KernelFormat>(rows, cols, depth, 1,
-                                    context->l1_bytes_to_use(),
-                                    context->l2_bytes_to_use(),
-                                    context->l2_rhs_factor());
-
     PackedLhs packed_lhs(Side::Lhs, local_allocator, block_params);
 
     PackedResult packed_result(local_allocator, block_params);
@@ -483,6 +480,7 @@ struct GemmWithPackedRhsTask : Task {
   const MatrixBlockBounds result_block;
   const LhsOffset& lhs_offset;
   const RhsOffset& rhs_offset;
+  const BlockParams& block_params;
   const OutputPipelineType& output_pipeline;
 };
 
@@ -695,7 +693,7 @@ void MultiThreadGemm(GemmContextType* context, const KernelBase& kernel,
           TaskType;
       auto task = new TaskType(context, kernel, lhs_block, packed_rhs, result,
                                MatrixBlockBounds(start_row, c, block_rows, cs),
-                               lhs_offset, rhs_offset, output_pipeline);
+                               lhs_offset, rhs_offset, block_params, output_pipeline);
       if (thread < workers_count) {
         workers_pool->StartWorker(thread, task);
       } else {
```

**Comment by andreasgal** [comment]
(You also removed the l2_col blocking loop, I didn't find that to help and in theory it can also push us above L2 cache size)

**Comment by bjacob** [comment]
I see. Does that fix both the performance regression from my commit, and the correctness issue that you had reported earlier and that my commit fixed?

**Comment by andreasgal** [comment]
Let me try to run the original test I was using

**Comment by andreasgal** [comment]
All tests with this change:

-const int kDefaultL2CacheSize = 4 * 1024 * 1024;
+const int kDefaultL2CacheSize = 128 * 1024;

HEAD=9bdbf330c00858c02ba92aac5d2a129ef261e5cc (without bjacob's fix)

test.x86 fails as expected:

bad coeff: at (9, 18), expected 66, got 72
gemmlowp error: test failed at test/test.cc:490
Abort trap: 6

with this patch:

```patch
diff --git a/internal/block_params.h b/internal/block_params.h
index b2fc3ff..4e1b494 100644
--- a/internal/block_params.h
+++ b/internal/block_params.h
@@ -61,6 +61,10 @@ struct BlockParams {
     int l2_rows = 0;
     int l2_cols = 0;
     int l2_depth = 0;
+
+    int per_thread_rows =
+      std::max(1, RoundUp<KernelFormat::kRows>(rows) / num_threads);
+
     // No L2 blocking in the depth dimension at the moment.
     // Too much loss of accuracy due to storing intermediate results in
     // low precision.
@@ -81,15 +85,15 @@ struct BlockParams {
     // dimension concerns only the LHS. Blocking only RHS matrix for L2 enhances
     // the performance on x86.
     if (l2_rhs_factor == 1.0f) {
-      l2_rows = RoundUp<KernelFormat::kRows>(rows);
+      l2_rows = RoundUp<KernelFormat::kRows>(per_thread_rows);
     } else {
       int max_cache_friendly_l2_rows =
           std::max(1, (l2_bytes_to_use - l2_depth * l2_cols) /
                           (num_threads * (l2_depth + 4 * l2_cols)));
       int min_l2_rows_blocks =
-          std::max(1, CeilQuotient(rows, max_cache_friendly_l2_rows));
+          std::max(1, CeilQuotient(per_thread_rows, max_cache_friendly_l2_rows));
       l2_rows =
-          RoundUp<KernelFormat::kRows>(CeilQuotient(rows, min_l2_rows_blocks));
+          RoundUp<KernelFormat::kRows>(CeilQuotient(per_thread_rows, min_l2_rows_blocks));
     }
 
     *out_l2_rows = l2_rows;
diff --git a/internal/common.h b/internal/common.h
index 2fdaa1c..388ff13 100644
--- a/internal/common.h
+++ b/internal/common.h
@@ -172,7 +172,7 @@ const int kDefaultL2CacheSize = 384 * 1024;
 // Thus we assume larger cache sizes, though we really should query
 // them at runtime.
 const int kDefaultL1CacheSize = 32 * 1024;
-const int kDefaultL2CacheSize = 4 * 1024 * 1024;
+const int kDefaultL2CacheSize = 128 * 1024;
 #elif defined(GEMMLOWP_X86_32)
 // x86-32 and not Android. Same as x86-64 but less bullish.
 const int kDefaultL1CacheSize = 32 * 1024;
diff --git a/internal/multi_thread_gemm.h b/internal/multi_thread_gemm.h
index 749c635..a80cac0 100644
--- a/internal/multi_thread_gemm.h
+++ b/internal/multi_thread_gemm.h
@@ -439,6 +439,7 @@ struct GemmWithPackedRhsTask : Task {
                         const MatrixBlockBounds& _result_block,
                         const LhsOffset& _lhs_offset,
                         const RhsOffset& _rhs_offset,
+                        const BlockParams& _block_params,
                         const OutputPipelineType& _output_pipeline)
       : context(_context),
         kernel(_kernel),
@@ -448,6 +449,7 @@ struct GemmWithPackedRhsTask : Task {
         result_block(_result_block),
         lhs_offset(_lhs_offset),
         rhs_offset(_rhs_offset),
+        block_params(_block_params),
         output_pipeline(_output_pipeline) {}
 
   void Run() override {
@@ -457,12 +459,6 @@ struct GemmWithPackedRhsTask : Task {
     const int cols = result_block.cols;
     const int depth = lhs.cols();
 
-    BlockParams block_params;
-    block_params.Init<KernelFormat>(rows, cols, depth, 1,
-                                    context->l1_bytes_to_use(),
-                                    context->l2_bytes_to_use(),
-                                    context->l2_rhs_factor());
-
     PackedLhs packed_lhs(Side::Lhs, local_allocator, block_params);
 
     PackedResult packed_result(local_allocator, block_params);
@@ -501,6 +497,7 @@ struct GemmWithPackedRhsTask : Task {
   const MatrixBlockBounds result_block;
   const LhsOffset& lhs_offset;
   const RhsOffset& rhs_offset;
+  const BlockParams& block_params;
   const OutputPipelineType& output_pipeline;
 };
 
@@ -693,7 +690,7 @@ void MultiThreadGemm(GemmContextType* context, const KernelBase& kernel,
           TaskType;
       tasks.push_back(new TaskType(context, kernel, lhs_block, packed_rhs, result,
                                    MatrixBlockBounds(start_row, c, block_rows, cs),
-                                   lhs_offset, rhs_offset, output_pipeline));
+                                   lhs_offset, rhs_offset, block_params, output_pipeline));
     }
     // Execute the work on the workers (and partially on this thread).
     workers_pool->Execute(tasks);
```

Error in 64..127 range: 0.00 % of entries
Error in 128..255 range: 0.00 % of entries
All tests passed.

Performance with my patch is about the same as without.

**Comment by bjacob** [comment]
Excellent! Do you want to make a pull request or allow me to commit that under your identity --- I'd like to pull that in ASAP.

**Comment by andreasgal** [comment]
Feel free to push under your name or mine or whatever. You found and fixed this bug. I just removed pieces until it also worked for my constraints :) Thanks!

**Comment by bjacob** [comment]
At your convenience, please give your agreement on https://github.com/google/gemmlowp/pull/109

**Comment by bjacob** [comment]
Merged, fixed.
