### ISSUE TITLE
Reconsider GEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK

### ISSUE THREAD

**Issue by jart** [google/gemmlowp#117]
Is there any chance the authors of gemmlowp would consider removing the `#error` directive that halts non-optimized builds? It's not a common practice. I'd like for it to be possible to build TensorFlow without passing any special configuration directives. Perhaps consider printing a big ASCII art skull and crossbones [`#warning`](https://stackoverflow.com/questions/171435/portability-of-warning-preprocessor-directive) instead? Sort of like [Gosling Emacs](https://gist.github.com/jart/0a6a402b480e7dbcf8e61895759f2058)?

cc: @gunan

**Comment by jart** [comment]
It seems seven other bugs have been opened and ten files in TensorFlow codebase alone have local workarounds for this flag. I'm going to send a PR.

**Comment by bjacob** [comment]
Merged. Thanks for bringing this up and writing the patch.
This was done initially as we were concerned that many users would inadvertently miss out on the SIMD paths, and would rather know. However, this has since caused much trouble, and I was regretting it already.

**Comment by jart** [comment]
It was definitely done with best intentions. Hopefully we'll be able to accomplish this on the TensorFlow end by creating additional pip packages for each CPU microarchitecture.
