### ISSUE TITLE
is only conv layer supported?

### ISSUE THREAD

**Issue by yfyan0204** [google/gemmlowp#158]
Great Thanks for sharing the knowledge about gemmlowp.
I have a question described as below.
How to do the fixed-point arithmetic the other layers (such as shortcut/routine/upsample...) in networks not only in conv layers?
for example the arithmetic  in shortcut layer, the inputs are layer A and layer B, but the range of the 2 layers are not same. Is there any way to process such scenarios?

great thanks if someone can help.

**Comment by bjacob** [comment]
gemmlowp is only a matrix multiplication library. the general question of implementing quantized nn layers is more the focus of TensorFlow Lite.  See its runtime code there --- suggest starting with reference/reference_ops.h.
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/kernels/internal
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/reference/reference_ops.h

**Comment by yfyan0204** [comment]
Thanks a lot.
