### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by dibya001** [google/gemmlowp#182]
As python 3 going to be unsupported in Jan 2020, so is there any plan of upgrading the few python scripts inside the meta/generators folder to support python 3?
The changes looks to be only the print statements ones when I ran the 2to3 tool
For example:- https://github.com/google/gemmlowp/blob/master/meta/generators/cc_emitter.py

**Comment by bjacob** [comment]
I don't know that meta/ is maintained at the moment. Feel free to make a pull request.

**Comment by dibya001** [comment]
Raised a pull request.(Merged now). Hence closing this issue.
