### ISSUE TITLE
Issues compiling for bare metal application

### ISSUE THREAD

**Issue by wrd90** [google/gemmlowp#196]
Hi,

I am trying to compile TFLite for a bare metal application, and have run into issues with gemmlowp while doing so. For my target platform I do not have `unistd.h`, can anyone help me find a workaround?

**Comment by bjacob** [comment]
Does TFLite For Microcontrollers meet your needs?
https://www.tensorflow.org/lite/microcontrollers/get_started
Either way you should ask on a TFLite support channel - either if you overcame any issue with gemmlowp (just getting rid of a unistd.h include would be fairly easy), you would run into more issues with TFLite, which is much larger and has more OS dependencies. TFLite For Microcontrollers is meant to address this class of use cases.

**Comment by wrd90** [comment]
Hi @bjacob and thanks for your reply. You are right, I should have added more information regarding what I'm up to. I am trying to use tflite for microcontrollers on a new target (TM4C), and I haven't managed to figure out the dependencies that are truly necessary. For example 
`lite/kernels/internal/common.h` depends on gemmlowp. It's not in the `micro` folder, but in all of the examples I found some parts of the `lite` folder are still included, especially parts of the kernels. 
But yes, I might have to ask in the tensorflow project. Thanks anyway!
