### ISSUE TITLE
Suggestions for resources to understand gemmlowp

### ISSUE THREAD

**Issue by mrtpk123** [google/gemmlowp#210]
Hello,

I'm a noob trying to understand the theory and implementation of gemmlowp. Can you please share any resources that I can start with?
Any help in this regard is very much appreciated.

Thanks,
Thomas.

**Comment by bjacob** [comment]
There are some design docs in the `doc/` directory, and the general idea of quantization has been elaborated on in https://arxiv.org/abs/1712.05877 and https://www.tensorflow.org/lite/performance/quantization_spec .

gemmlowp is obsolete though, its successor is https://github.com/google/ruy - also not design-documented, sorry. Also not very actively developed anymore at the moment. These days, an increasing fraction of the use cases is migrating to https://github.com/google/XNNPACK .

**Comment by mrtpk123** [comment]
Thank you
